[project]
name = "metadata-extraction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.78.1",
    "ruff>=0.11.10",
]
